places: list = ["londra","reykjavik","canarie","tokyo","amsterdam"] 
print(places)
print(sorted(places))
print(sorted(places, reverse= True))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(places, reverse= True)
print(places)